import { Octokit } from '@octokit/rest';
import { spawnSync } from 'child_process';
import { loadConfig, getToken } from './config.js';
import type { Issue } from './intake.js';

function slugify(text: string): string {
  const slug = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30).replace(/-$/, '');
  return slug || 'issue';
}

function git(...args: string[]): string {
  const result = spawnSync('git', args, { encoding: 'utf-8' });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(result.stderr || `git ${args[0]} failed`);
  return result.stdout.trim();
}

function branchExists(branchName: string): boolean {
  const result = spawnSync('git', ['rev-parse', '--verify', branchName], { encoding: 'utf-8' });
  return result.status === 0;
}

async function findExistingPR(octokit: Octokit, owner: string, repo: string, head: string): Promise<number | null> {
  const { data: prs } = await octokit.pulls.list({ owner, repo, head: `${owner}:${head}`, state: 'open' });
  return prs.length > 0 ? prs[0].number : null;
}

export async function createBranchAndPR(issue: Issue, prDescription?: string, credits?: number, timeSeconds?: number): Promise<string> {
  const token = getToken();
  const config = loadConfig();
  const branchName = `agent/${issue.number}-${slugify(issue.title)}`;
  const octokit = new Octokit({ auth: token });

  const defaultBranch = git('rev-parse', '--abbrev-ref', 'HEAD');

  // Stash tracked changes only (exclude untracked files like .vibesprint)
  const hasChanges = spawnSync('git', ['diff', '--quiet'], { encoding: 'utf-8' }).status !== 0;
  if (hasChanges) git('stash');
  git('pull', '--rebase', 'origin', defaultBranch);
  if (hasChanges) {
    try {
      git('stash', 'pop');
    } catch {
      // Stash conflict - changes already applied
    }
  }

  // Always create fresh branch from main
  if (branchExists(branchName)) {
    git('checkout', defaultBranch);
    git('branch', '-D', branchName);
  }
  git('checkout', '-b', branchName);

  git('add', '-A');
  try {
    git('commit', '-m', `feat: ${issue.title}\n\nRefs #${issue.number}`);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    if (errorMsg.includes('nothing to commit')) {
      throw new Error('No changes were made by kiro-cli. Check if the issue was already resolved or needs clearer instructions.');
    }
    throw new Error(`Failed to commit changes: ${errorMsg}\n\nEnsure git user.name and user.email are configured:\n  git config --global user.name "Your Name"\n  git config --global user.email "your@email.com"`);
  }

  git('push', '-u', 'origin', branchName, '--force-with-lease');

  const creditsLine = credits !== undefined ? `\n\n---\n🤖 *Generated by VibeSprint* • Credits: ${credits} • Time: ${timeSeconds}s` : '';
  const body = (prDescription || `## Summary\n\n${issue.body || 'Auto-generated from issue.'}\n\nFixes #${issue.number}`) + creditsLine;

  // Check for existing PR
  const existingPrNumber = await findExistingPR(octokit, config.owner!, config.repo!, branchName);

  let prUrl: string;
  if (existingPrNumber) {
    await octokit.pulls.update({
      owner: config.owner!,
      repo: config.repo!,
      pull_number: existingPrNumber,
      body,
    });
    prUrl = `https://github.com/${config.owner}/${config.repo}/pull/${existingPrNumber}`;
  } else {
    const { data: pr } = await octokit.pulls.create({
      owner: config.owner!,
      repo: config.repo!,
      title: issue.title,
      body,
      head: branchName,
      base: defaultBranch,
    });
    prUrl = pr.html_url;
  }

  git('checkout', defaultBranch);
  return prUrl;
}
