import { spawnSync } from 'child_process';
import { loadConfig } from './config.js';
import { gh, ghJson } from './utils/gh.js';
import type { Issue } from './intake.js';

function slugify(text: string): string {
  const slug = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30).replace(/-$/, '');
  return slug || 'issue';
}

function git(...args: string[]): string {
  const result = spawnSync('git', args, { encoding: 'utf-8' });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(result.stderr || `git ${args[0]} failed`);
  return result.stdout.trim();
}

function branchExists(branchName: string): boolean {
  const result = spawnSync('git', ['rev-parse', '--verify', branchName], { encoding: 'utf-8' });
  return result.status === 0;
}

function findExistingPR(branchName: string): number | null {
  const result = ghJson<Array<{ number: number; headRefName: string }> | { pullRequests: Array<{ number: number }> }>([
    'pr', 'list', '--head', branchName, '--state', 'open', '--json', 'number,headRefName',
  ]);
  const prs = Array.isArray(result) ? result : result?.pullRequests || [];
  return prs.length > 0 ? prs[0].number : null;
}

export async function createBranchAndPR(issue: Issue, prDescription?: string, credits?: number, timeSeconds?: number): Promise<string> {
  const config = loadConfig();
  const branchName = `agent/${issue.number}-${slugify(issue.title)}`;

  const defaultBranch = git('rev-parse', '--abbrev-ref', 'HEAD');

  // Stash tracked changes only (exclude untracked files like .vibesprint)
  const hasChanges = spawnSync('git', ['diff', '--quiet'], { encoding: 'utf-8' }).status !== 0;
  if (hasChanges) git('stash');
  git('pull', '--rebase', 'origin', defaultBranch);
  if (hasChanges) {
    try {
      git('stash', 'pop');
    } catch {
      // Stash conflict - changes already applied
    }
  }

  // Always create fresh branch from main
  if (branchExists(branchName)) {
    git('checkout', defaultBranch);
    try {
      git('branch', '-D', branchName);
    } catch {
      // Branch might be in use by worktree - ignore and reuse
    }
  }
  
  try {
    git('checkout', '-b', branchName);
  } catch {
    // Branch already exists (couldn't delete) - just checkout
    git('checkout', branchName);
  }

  git('add', '-A');
  
  // Check if there are changes to commit
  const status = spawnSync('git', ['status', '--porcelain'], { encoding: 'utf-8' });
  if (!status.stdout.trim()) {
    // No changes - check if PR already exists (kiro may have created it)
    const existingPr = findExistingPR(branchName);
    if (existingPr) {
      git('checkout', defaultBranch);
      return `https://github.com/${config.owner}/${config.repo}/pull/${existingPr}`;
    }
    throw new Error('No changes were made by kiro-cli. Check if the issue was already resolved or needs clearer instructions.');
  }
  
  try {
    git('commit', '-m', `feat: ${issue.title}\n\nRefs #${issue.number}`);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to commit changes: ${errorMsg}\n\nEnsure git user.name and user.email are configured:\n  git config --global user.name "Your Name"\n  git config --global user.email "your@email.com"`);
  }

  git('push', '-u', 'origin', branchName, '--force-with-lease');

  const creditsLine = credits !== undefined ? `\n\n---\n🤖 *Generated by VibeSprint* • Credits: ${credits} • Time: ${timeSeconds}s` : '';
  const body = (prDescription || `## Summary\n\n${issue.body || 'Auto-generated from issue.'}\n\nFixes #${issue.number}`) + creditsLine;

  // Check for existing PR
  const existingPrNumber = findExistingPR(branchName);

  let prUrl: string;
  if (existingPrNumber) {
    gh(['pr', 'edit', String(existingPrNumber), '--body', body]);
    prUrl = `https://github.com/${config.owner}/${config.repo}/pull/${existingPrNumber}`;
  } else {
    const prResult = gh([
      'pr', 'create',
      '--title', issue.title,
      '--body', body,
      '--head', branchName,
      '--base', defaultBranch,
    ]);
    if (!prResult.success) {
      throw new Error(`Failed to create PR: ${prResult.stderr}`);
    }
    // Extract URL from output
    const urlMatch = prResult.stdout.match(/https:\/\/github\.com\/[^\s]+/);
    prUrl = urlMatch ? urlMatch[0] : `https://github.com/${config.owner}/${config.repo}/pulls`;
  }

  git('checkout', defaultBranch);
  return prUrl;
}
